### ISSUE TITLE
object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by kytwb** [nortxort/nortbot#11]
```
[10:50:27:970] <redacted>: !yts elliot lipp
object of type 'NoneType' has no len()
```

**Comment by nortxort** [comment]
I guess it was just a matter of time before it would happen. The problem is when trying to validate if the search term is a youtube ID. This was done using len() `if len(search_term) == 11: return True` and your search string(elliot lipp) was exactly 11 characters long, but since that was clearly not a youtube ID it just returned None. I have changed the validation to use regex instead, it might not be perfect but i hope itll work somewhat better.

Thanks.

**Comment by kytwb** [comment]
Got it, thanks for patching!
