### ISSUE TITLE
[Suggestion] VIP Mode

### ISSUE THREAD

**Issue by Technetium1** [nortxort/nortbot#52]
**Is your feature request related to a problem? Please describe.**
* People would like a way to temporarily make a room private without logging into the owner account to set a password that must then be shared.

**Describe the solution you'd like**
* A VIP mode that when triggered causes every new join to be kicked/banned if they are not a moderator or in `approved_accounts`.

**Describe alternatives you've considered**
* ~~A separate file for people that are allowed in VIP mode; but that seems very excessive for no good reason...~~ ***Edit:*** There many be a good reason

**Additional context**
* People that are already in the room when VIP is triggered should not be banned/kicked. 
* Have the kick/ban depend on `KickAsAutoban` config option.

**Comment by Technetium1** [comment]
Added in https://github.com/nortxort/nortbot/commit/2b2d3fa1aec9d2247170aa9dd0a8a6640b5dc8f2!

**Comment by Autotonic** [comment]
Got em

**Comment by Treekss** [comment]
A separate file unrelated to the approved accounts list is not excessive and actually very necessary, because not everyone who is allowed in during VIP mode needs to automatically have bot control, and without a separate list you end up kicking/banning non-bot-controlling regulars if they lose connection or refresh while VIP is active. This all seems problematic and essentially useless without a separate list solely dedicated to VIP exceptions and nothing else.

**Comment by nortxort** [comment]
Feel free to implemeted it.

**Comment by nortxort** [comment]
This has been implemented as described. @Treekss if you want it differently, you may implement it.
